apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:8.11.3
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-svc.sre.svc.cluster.local:9200"
        ports:
        - containerPort: 5601
        readinessProbe:
          httpGet:
            path: /api/status
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: kibana-config