apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-oap
  labels:
    app: skywalking-oap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking-oap
  template:
    metadata:
      labels:
        app: skywalking-oap
    spec:
      serviceAccountName: skywalking-oap-serviceaccount
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: skywalking-oap
      initContainers:
      - name: wait-for-elasticsearch
        image: busybox:1.36.1
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'for i in $(seq 1 60); do nc -z -w3 elasticsearch-svc 9200 && exit 0 || sleep 5; done; exit 1']
      containers:
      - name: skywalking-oap
        image: apache/skywalking-oap-server:9.6.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 12800
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 12800
          failureThreshold: 9
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 12800
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 11800
          name: grpc
        - containerPort: 12800
          name: rest
        env:
        - name: JAVA_OPTS
          value: "-Dmode=no-init -Xmx2g -Xms2g"
        - name: SW_CLUSTER
          value: kubernetes
        - name: SW_CLUSTER_K8S_NAMESPACE
          value: "sre"
        - name: SW_CLUSTER_K8S_LABEL
          value: "app=skywalking-oap"
        - name: SKYWALKING_COLLECTOR_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: SW_STORAGE
          value: elasticsearch
        - name: SW_STORAGE_ES_CLUSTER_NODES
          value: "elasticsearch-svc:9200"
        #- name: SW_ES_USER
        #  value: "{{ .Values.elasticsearch.config.user }}"
        #- name: SW_ES_PASSWORD
        #  value: "{{ .Values.elasticsearch.config.password }}"