apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: skywalking-oap-role
  labels:
    app: skywalking-oap
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps"]
    verbs: ["get", "watch", "list"]