apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skywalking-oap-rolebinding
  labels:
    app: skywalking-oap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skywalking-oap-role
subjects:
  - kind: ServiceAccount
    name: skywalking-oap-serviceaccount
    namespace: sre