apiVersion: v1
kind: Service
metadata:
  name: skywalking-ui-svc
  labels:
    app: skywalking-ui
spec:
  type: ClusterIP
  selector:
    app: skywalking-ui
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP